# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NqXRsZxkEOvAanO1xCuMXd2ZyTA3VguL
"""

print ('Hello, world')

length = 10
width = 2
name = "saturnus"

def greeting(name):
  return 'hello,' + name

print(greeting('bangkit'))

a = 10
b = 30.0
a + b

print(1 < 10 )

print (1 != "1")

print ("Linux" == "Windows")

def check(number):
  if number > 0:
    return "Positive"
  elif number == 0:
    return "Zero"
  else:
    return "negative"

x = 7

while x > 0:
  print("positive x=" + str(x))
  x = x - 1

print("now x=" + str(x))

for x in range (3):
  print("x=" + str(x))



for x in range (3):
  print("x=" + str(x))
  if x == 1:
    break

for x in range(3,0,-1):
  if x % 2 == 0:
    continue
  print(x)

length = 10
width = 2
area = length * width

x = 10
y = 2
a = x*y

paths = ['ml', 'cloud']

print(paths[0])

paths = ['ml', 'cloud']

paths.append('android')

paths = ['ml', 'cloud']

paths.remove('cloud')

paths = ['ml', 'cloud']

paths.insert(1, 'mobile')

paths = ['ml', 'cloud']

paths.append('android')
paths.remove('cloud')
paths.insert(1, 'mobile')
paths.pop(-1)

students = {
    'ml' : 500,
    'mobile' : 700,
    'cloud' : 900
}

print(students['cloud'])